questweb/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

/*********************************************************
* Quest Web System routes
*
*********************************************************/

Route::get('/', array('as' => 'index', function()
{
	return View::make('index');
}));

Route::get('/login', array('as' => 'login', function()
{
	return View::make('login');
}));

Route::get('/internalLogin', array('as' => 'internalLogin', function()
{
	return View::make('internal_login');
}));

Route::post('login', array( 'uses' => 'UserController@loginAction'));
Route::any('prelogin', array( 'uses' => 'UserController@preLoginAction'));

Route::any('logout', array('as' => 'logout', 'uses' => 'UserController@logoutAction'));

Route::get('/home', array('before' => array('auth'), 'as' => 'home', function()
{
	return View::make('home');
}));

Route::get('/questCheck/{uid}', array('before' => array('auth'), 'as' => 'questCheck', function($uid)
{
	$test = KnownId::where("uid","=",$uid)->first();
	return Response::json(array("isQuest"=>!is_null($test)));
}));

Route::post('register', array( 'uses' => 'UserController@register'));

/*********************************************************
* Role Filters
*
*********************************************************/

Route::filter('applicant', function()
{
	$application = Application::where('name', '=', "Application 2015")->firstOrFail();
	if(!(strtotime($application->appStartDate()) < strtotime(date(DATE_RFC2822)) && strtotime($application->appDueDate()) >= strtotime(date(DATE_RFC2822)))){
		if(!is_null(Auth::user()->userApplication) && Auth::user()->userApplication->submitted){
			$message = "Thanks for your submission! Your application is currently being considered.";
			return View::make('home',array('message' => $message));
		} else {
			$message = "Applications are closed for this year.";
			return View::make('home',array('message' => $message));
		}
	}	
	if(!Auth::user()->isApplicant()){
		return Redirect::to('home'); 
	}
});

Route::filter('reader', function()
{
	if(!Auth::user()->isReader()){
		return Redirect::to('home'); 
	}
});

Route::filter('qualityguild', function()
{
	if(!Auth::user()->isQualityGuild()){
		return Redirect::to('home'); 
	}
});



/*********************************************************
* Quest Applications
*
*********************************************************/
//Applicants

Route::group(array('before' => array('auth', 'applicant')), function(){
	Route::resource('UserApplications', 'UserApplicationsController');
	Route::get('/UserApplications/{id}/delete', array('as' => 'UserApplications.delete', 'uses' => 'UserApplicationsController@destroy'));

});

//Quality Guild

Route::group(array('before' => array('auth', 'qualityguild')), function(){

	Route::get('/admin', array('as' => 'admin', function()
	{
		return View::make('QuestApplication.qualityguild.admin');
	}));
});

questweb/app/models/UserApplication.php
<?php

class UserApplication extends \Eloquent {

	// Add your validation rules here
	public static $rules = [
		// 'title' => 'required'
	];

	// Don't forget to fill this array
	protected $fillable = ['application_id','user_id','submitted'];

	public function application()
    {
        return $this->belongsTo('Application');
    }

    public function user()
    {
        return $this->belongsTo('User');
    }

    public function readers()
    {
        return $this->belongsToMany('User','reader_assignments','user_application_id','reviewer_id');
    }

	public function questions()
    {
    	$app = $this->application;
        return $app->questions;
    }

    public function readerCriterias()
    {
        $app = $this->application;
        return $app->readerCriterias;
    }

    public function answers()
    {
    	return $this->hasMany('Answer');
    }

}

questweb/app/views/QuestApplication/apply/userapplication/index.blade.php
@extends('layout')

@section('custHeader')
<style>
.col-centered{
	text-align: center;
}

</style>
@stop

@section('content')
<div class="container">
  <!-- Three columns of text below the carousel -->
  <div class="row">
	<div class="container marketing">
	  <!-- Three columns of text below the carousel -->
	  <div class="row">
		@if (Auth::user()->userApplication != null)
			<div class="col-md-4 col-centered">
		      <a href="{{ URL::route("UserApplications.show",Auth::user()->userApplication->id) }}">
		      <i class="fa fa-file-text" style="font-size:200px;"></i>
		      <h2>View Your Application</h2></a>
		    </div><!-- /.col-lg-4 -->
		    <div class="col-md-4 col-centered">
		      <a href="{{ URL::route("UserApplications.edit",Auth::user()->userApplication->id) }}">
		      <i class="fa fa-edit" style="font-size:200px;"></i>
		      <h2>Edit Your Application</h2></a>
		    </div><!-- /.col-lg-4 -->
		    <div class="col-md-4 col-centered">
		      <a href="{{ URL::route("UserApplications.delete",Auth::user()->userApplication->id) }}">
		      <i class="fa fa-trash" style="font-size:200px;"></i>
		      <h2>Delete Your Application</h2></a>
		    </div><!-- /.col-lg-4 -->
		@else
		    <div class="col-xs-12 col-centered">
		      <a href="{{ URL::route("UserApplications.create") }}">
		      <i class="fa fa-sign-in" style="font-size:200px;"></i>
		      <h2>Create Your Application</h2></a>
		    </div><!-- /.col-lg-4 -->
		@endif
	  </div><!-- /.row -->
	</div>
  </div><!-- /.row -->
</div>
@stop

questweb/app/views/QuestApplication/apply/userapplication/show.blade.php
@extends('layout')

@section('custHeader')
<style>
.offset{
	margin-top:45px;
	background-color:#222;
}
body > .container {
	margin-top:70px;
}
.col-centered{
	text-align: center;
}
.btn {
	width:100%;
}
</style>
@stop

@section('content')
<div class="container offset-container">
  <!-- Three columns of text below the carousel -->
	<?php $i = 0; ?>

	<div class="navbar navbar-fixed-top offset" role="navigation">
      <div class="container" style="margin-top: 10px;">
        <div class="navbar-collapse collapse">
			<div class="row">
				<div class="col-xs-4 col-centered col-xs-offset-4">
					<a class="btn btn-default btn-sm" href="{{ URL::route("UserApplications.edit",Auth::user()->userApplication->id) }}">
					Edit
		  			</a>
				</div>
			</div>
        </div>
      </div>
    </div>

    @if($userapplication->submitted == true)
    	<div class="row">
    		<div class="col-xs-12">
    			<table class="table">
    				<tr>
    					<td class="danger">This application has been submitted. You have untill {{ $userapplication->application()->get()[0]->appDueDate() }} to unsubmit it.</td>
    				</tr>
    			</table>
    		</div>
    	</div>
    @endif


    @foreach($userapplication->questions() as $question)
    	<div class="row">
		  <div class="col-xs-6">
		  	<h4>
		  	{{ $i + 1 . ".) " . $question->question_html }}
		  	</h4>
		  </div>
		  <div class="col-xs-6">
		  	<p>
		  	{{ $userapplication->answerForQuestion($question->id) }}
		  	</p>
		  </div><!-- /.col-lg-4 -->
    	</div><!-- /.row -->
    	<hr/>
    	<?php $i = $i + 1; ?>
   	@endforeach
</div>
@stop